#!/bin/bash
# Generated by fc_parse.sh in dir /works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign

frama-c -machdep x86_64 -cpp-command 'gcc -C -E -I. -DEOF=-1 -D__FC_FOPEN_MAX=512 -D__FC_MAX_OPEN_FILES=1024 -DF_DUPFD=1 -DF_GETFD=2 -DF_SETFD=3 -DF_GETFL=4 -DF_SETFL=5 -DF_GETLK=6 -DF_SETLK=7 -DF_SETLKW=8 -DF_GETOWN=9 -DF_SETOWN=10 -DO_CREAT=0x0200' \
./build/test_saml_sign.ut.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/dict.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/threads.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/valid.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/parser.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/entities.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/catalog.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/validate_saml_sign.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/uri.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/error.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/buf.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/SAX.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/globals.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/parserInternals.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/hash.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/xmlstring.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/tree.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/SAX2.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/xmlmemory.i.c \
/works/home/balp/third_parties/llvm/tools/clang/tools/extra/callers/tests/test_saml_sign/build/list.i.c \
-pp-annot -save fc_parsed.gen.sav
