#!/bin/bash
# Generated by fc_parse.sh in dir /data/balp/src/tools/libxml2-2.9.3

#frama-c -frama-c-stdlib \
frama-c -machdep x86_64 -cpp-command 'gcc -C -E -I. -DEOF=-1 -D__FC_FOPEN_MAX=512 -D__FC_MAX_OPEN_FILES=1024 -DF_DUPFD=1 -DF_GETFD=2 -DF_SETFD=3 -DF_GETFL=4 -DF_SETFL=5 -DF_GETLK=6 -DF_SETLK=7 -DF_SETLKW=8 -DF_GETOWN=9 -DF_SETOWN=10 -DO_CREAT=0x0200' \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xlink.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlschemas.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/list.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/SAX.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/uri.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/nanoftp.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlschemastypes.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlwriter.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/dict.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/nanohttp.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/buf.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/relaxng.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/parserInternals.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/entities.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/parser.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/error.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xpointer.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/valid.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/chvalid.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlsave.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xpath.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/pattern.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlreader.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlstring.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/catalog.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlregexp.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/HTMLtree.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlmemory.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/debugXML.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/SAX2.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/hash.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/tree.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlIO.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/HTMLparser.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/c14n.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/encoding.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/schematron.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xinclude.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/threads.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xzlib.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlunicode.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/xmlmodule.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/globals.i.c \
 /home/hbalp/hugues/work/third_parties/src/libxml2/legacy.i.c \
 ./build/test_saml_sign.ut.i.c \
 ./build/validate_saml_sign.i.c \
 -pp-annot -save fc_parsed.gen.sav
