#!/bin/bash
# Generated by fc_parse.sh in dir /data/balp/src/tools/libxml2-2.9.3

#frama-c -frama-c-stdlib \
frama-c -machdep x86_64 -cpp-command 'gcc -C -E -I. -DEOF=-1 -D__FC_FOPEN_MAX=512 -D__FC_MAX_OPEN_FILES=1024 -DF_DUPFD=1 -DF_GETFD=2 -DF_SETFD=3 -DF_GETFL=4 -DF_SETFL=5 -DF_GETLK=6 -DF_SETLK=7 -DF_SETLKW=8 -DF_GETOWN=9 -DF_SETOWN=10 -DO_CREAT=0x0200' \
/data/balp/src/tools/libxml2-2.9.3/HTMLparser.i.c \
/data/balp/src/tools/libxml2-2.9.3/HTMLtree.i.c \
/data/balp/src/tools/libxml2-2.9.3/SAX.i.c \
/data/balp/src/tools/libxml2-2.9.3/SAX2.i.c \
/data/balp/src/tools/libxml2-2.9.3/buf.i.c \
/data/balp/src/tools/libxml2-2.9.3/c14n.i.c \
/data/balp/src/tools/libxml2-2.9.3/catalog.i.c \
/data/balp/src/tools/libxml2-2.9.3/chvalid.i.c \
/data/balp/src/tools/libxml2-2.9.3/debugXML.i.c \
/data/balp/src/tools/libxml2-2.9.3/dict.i.c \
/data/balp/src/tools/libxml2-2.9.3/encoding.i.c \
/data/balp/src/tools/libxml2-2.9.3/entities.i.c \
/data/balp/src/tools/libxml2-2.9.3/error.i.c \
/data/balp/src/tools/libxml2-2.9.3/globals.i.c \
/data/balp/src/tools/libxml2-2.9.3/hash.i.c \
/data/balp/src/tools/libxml2-2.9.3/legacy.i.c \
/data/balp/src/tools/libxml2-2.9.3/list.i.c \
/data/balp/src/tools/libxml2-2.9.3/nanoftp.i.c \
/data/balp/src/tools/libxml2-2.9.3/nanohttp.i.c \
/data/balp/src/tools/libxml2-2.9.3/parser.i.c \
/data/balp/src/tools/libxml2-2.9.3/parserInternals.i.c \
/data/balp/src/tools/libxml2-2.9.3/pattern.i.c \
/data/balp/src/tools/libxml2-2.9.3/relaxng.i.c \
/data/balp/src/tools/libxml2-2.9.3/schematron.i.c \
/data/balp/src/tools/libxml2-2.9.3/threads.i.c \
/data/balp/src/tools/libxml2-2.9.3/tree.i.c \
/data/balp/src/tools/libxml2-2.9.3/uri.i.c \
/data/balp/src/tools/libxml2-2.9.3/valid.i.c \
/data/balp/src/tools/libxml2-2.9.3/xinclude.i.c \
/data/balp/src/tools/libxml2-2.9.3/xlink.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlIO.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlmemory.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlmodule.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlreader.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlregexp.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlsave.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlschemas.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlschemastypes.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlstring.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlunicode.i.c \
/data/balp/src/tools/libxml2-2.9.3/xmlwriter.i.c \
/data/balp/src/tools/libxml2-2.9.3/xpath.i.c \
/data/balp/src/tools/libxml2-2.9.3/xpointer.i.c \
/data/balp/src/tools/libxml2-2.9.3/xzlib.i.c \
./build/test_saml_sign.i.c \
./fc_main.gen.i.c \
-pp-annot -save fc_parsed.gen.sav
